[custom]
;====================
; 规则集定义
;====================
ruleset=🏠 内网直连,[]DOMAIN-SUFFIX,local
ruleset=🏠 内网直连,[]IP-CIDR,10.0.0.0/8,no-resolve
ruleset=🏠 内网直连,[]IP-CIDR,192.168.0.0/16,no-resolve
ruleset=🏠 内网直连,[]IP-CIDR,127.0.0.0/8,no-resolve

ruleset=📹 YOUTUBE,[]DOMAIN-SUFFIX,youtube.com
ruleset=📹 YOUTUBE,[]DOMAIN-SUFFIX,googlevideo.com
ruleset=📹 YOUTUBE,[]DOMAIN-SUFFIX,youtube-nocookie.com
ruleset=📹 YOUTUBE,[]DOMAIN-SUFFIX,youtubeusercontent.com
ruleset=📹 YOUTUBE,[]DOMAIN-KEYWORD,youtube
ruleset=📹 YOUTUBE,[]IP-CIDR,172.110.32.0/21,no-resolve
ruleset=📹 YOUTUBE,[]IP-CIDR,216.73.80.0/20,no-resolve
ruleset=📹 YOUTUBE,[]IP-CIDR,142.250.0.0/16,no-resolve

ruleset=👥 Teams,[]DOMAIN-KEYWORD,teams.microsoft.com
ruleset=👥 Teams,[]DOMAIN-SUFFIX,teams.microsoft.com

ruleset=🤖 openai,[]DOMAIN-KEYWORD,chatgpt
ruleset=🤖 openai,[]IP-CIDR,104.18.0.0/16,no-resolve
ruleset=🤖 openai,[]IP-CIDR,160.79.0.0/16,no-resolve
ruleset=🤖 openai,[]DOMAIN-KEYWORD,cursor
ruleset=🤖 openai,[]IP-CIDR,107.148.47.3/32,no-resolve
ruleset=🤖 openai,[]DOMAIN-KEYWORD,claude

ruleset=🖥️ splashtop,[]DOMAIN-KEYWORD,splashtop

ruleset=🌐 节点选择,[]IP-CIDR,0.0.0.0/0,no-resolve
ruleset=🌐 节点选择,[]MATCH

;====================
; 策略组定义
;====================
custom_proxy_group=🌐 节点选择`select`.*
custom_proxy_group=📹 YOUTUBE`select`[]🌐 节点选择`.*
custom_proxy_group=👥 Teams`select`[]🌐 节点选择`.*
custom_proxy_group=🤖 openai`select`[]🌐 节点选择`.*
custom_proxy_group=🖥️ splashtop`select`[]🌐 节点选择`.*
custom_proxy_group=🏠 内网直连`select`[]DIRECT

;====================
; 其他设置
;====================
enable_rule_generator=true
overwrite_original_rules=true
clash_rule_base=https://raw.githubusercontent.com/vetus2/shuaishuai21313123/refs/heads/main/GeneralClashConfig.yml
